// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtqrqDCG7CobiiCflculr7nsj3GRw7nY',
    appId: '1:429711374363:web:5bf248866dc2d75cdfe0be',
    messagingSenderId: '429711374363',
    projectId: 'inclass14-5b9e8',
    authDomain: 'inclass14-5b9e8.firebaseapp.com',
    storageBucket: 'inclass14-5b9e8.firebasestorage.app',
    measurementId: 'G-XBSK21EBLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJRqUQs6fIF3eIgiAcfmdBAywMF6W16uU',
    appId: '1:429711374363:android:b2b869152b0eb197dfe0be',
    messagingSenderId: '429711374363',
    projectId: 'inclass14-5b9e8',
    storageBucket: 'inclass14-5b9e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp-4SpBX54t30PIIMhJ8BT_F5O48RnUp4',
    appId: '1:429711374363:ios:2d256df4c21d01b7dfe0be',
    messagingSenderId: '429711374363',
    projectId: 'inclass14-5b9e8',
    storageBucket: 'inclass14-5b9e8.firebasestorage.app',
    iosBundleId: 'com.example.inclass14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp-4SpBX54t30PIIMhJ8BT_F5O48RnUp4',
    appId: '1:429711374363:ios:2d256df4c21d01b7dfe0be',
    messagingSenderId: '429711374363',
    projectId: 'inclass14-5b9e8',
    storageBucket: 'inclass14-5b9e8.firebasestorage.app',
    iosBundleId: 'com.example.inclass14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHtqrqDCG7CobiiCflculr7nsj3GRw7nY',
    appId: '1:429711374363:web:c332ce50ed829e6edfe0be',
    messagingSenderId: '429711374363',
    projectId: 'inclass14-5b9e8',
    authDomain: 'inclass14-5b9e8.firebaseapp.com',
    storageBucket: 'inclass14-5b9e8.firebasestorage.app',
    measurementId: 'G-KGGDYV43N1',
  );
}
